version: '3.7'


services:
  main:
    image: postgres:14.1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./main:/var/lib/postgresql/data/pgdata
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    networks:
      sharding_network:


  shard_1:
    image: postgres:14.1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
      PGPORT: 5433
    ports:
      - "5433:5433"
    volumes:
      - ./shard_1:/var/lib/postgresql/data/pgdata
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    networks:
      sharding_network:
        aliases:
          - shard_1

  shard_2:
    image: postgres:14.1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
      PGPORT: 5434
    ports:
      - "5434:5434"
    volumes:
      - ./shard_2:/var/lib/postgresql/data/pgdata
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    networks:
      sharding_network:
        aliases:
          - shard_2


networks:
  sharding_network:
    driver: bridge
